### PR TITLE
:art: Adding dashboard image to notebook

### PR DESCRIPTION
**Pull request by Blaizzy**
How about this image?
I think instead of the gif I will explain everything in the docs video

### CODE REVIEW

**Comment by Blaizzy** [comment]
Perhaps adding a link to the video under the image ??

**Comment by jakubczakon** [comment]
@Blaizzy I think this is a great idea!

So I am 100% on adding a screenshot of the dashboard. 
I'm just not sure if this dashboard shows any value that neptune brings. 

Perhaps we should have a custom dashboard created for this project that has;
* learning curves batch level
* learning curves epoch level
* hardware consumption
* model parameters
* anything else that is logged?

It would be great to have it as then we could just show the value on one dashboard almost. 

What do you think?

**Comment by jakubczakon** [comment]
@Blaizzy https://www.loom.com/share/0c71c511a2c2492287d92a1a73d23752

**Comment by jakubczakon** [comment]
@Blaizzy there is no screenshot of the dashboard (value from this integration) nor a link to the exp dashboard. 
Could you please add it?

**Review by jakubczakon — APPROVED** [review]

**Pull request merged**
