### PR TITLE
Fix for Compare_model_training_runs_on_dataset_versions

### PR DESCRIPTION
**Pull request by SiddhantSadangi**
# Description

* Downloading data during runtime
* Handling path resolution for all execution modes (and taking into account [neptune issue with tracking windows absolute paths](https://docs.neptune.ai/logging/artifacts/#passing-an-absolute-windows-file-path))

__Related to:__ `fix test errors`

__Any expected test failures?__
All failures are intentional `AssertionError`s

---

Add a `[X]` to relevant checklist items

## ❔ This change

- [ ] adds a new feature
- [X] fixes breaking code
- [ ] is cosmetic (refactoring/reformatting)

---

## ✔️ Pre-merge checklist

- [X] Refactored code ([sourcery](https://sourcery.ai/))
- [X] Tested code locally
- [X] Precommit installed and run before pushing changes
- [ ] Added code to GitHub tests ([notebooks](workflows/test-notebooks.yml), [scripts](workflows/test-scripts.yml))
- [ ] Updated GitHub [README](../README.md)
- [ ] Updated the projects overview page on Notion

---

## 🧪 Test Configuration

- OS: Windows11
- Python version: 3.8.15
- Neptune version:
- Affected libraries with version:

### CODE REVIEW

**Review by kshitij12345 — CHANGES_REQUESTED** [review]
I think we should remove the files which are being downloaded now.

**Comment by SiddhantSadangi** [comment]
> I think we should remove the files which are being downloaded now.

the files are being downloaded from GitHub itself :)

**Comment by kshitij12345** [comment]
Right 🤦

**Review by kshitij12345 — APPROVED** [review]
LGTM! Thank you @SiddhantSadangi

**Pull request merged**
